config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :introductions
  resources :employees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :employees

  INTRODUCTIONS_PER_DAY = 3
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :company
  has_and_belongs_to_many :introductions
end

app/models/introduction.rb
class Introduction < ApplicationRecord
  has_and_belongs_to_many :employees

  after_create :set_scheduled_intro_date

  private

  def set_scheduled_intro_date
    SetScheduleIntroDateJob.perform_later(self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:is_being_onboarded, :what_i_do, :fun_fact, :slack_username)
    end
end

app/controllers/introductions_controller.rb
class IntroductionsController < ApplicationController
  before_action :set_introduction, only: [:show, :edit, :update, :destroy]

  # GET /introductions
  # GET /introductions.json
  def index
    @introductions = Introduction.all
  end

  # GET /introductions/1
  # GET /introductions/1.json
  def show
  end

  # GET /introductions/new
  def new
    @introduction = Introduction.new
  end

  # GET /introductions/1/edit
  def edit
  end

  # POST /introductions
  # POST /introductions.json
  def create
    @introduction = Introduction.new(introduction_params)

    respond_to do |format|
      if @introduction.save
        format.html { redirect_to @introduction, notice: 'Introduction was successfully created.' }
        format.json { render :show, status: :created, location: @introduction }
      else
        format.html { render :new }
        format.json { render json: @introduction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /introductions/1
  # PATCH/PUT /introductions/1.json
  def update
    respond_to do |format|
      if @introduction.update(introduction_params)
        format.html { redirect_to @introduction, notice: 'Introduction was successfully updated.' }
        format.json { render :show, status: :ok, location: @introduction }
      else
        format.html { render :edit }
        format.json { render json: @introduction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /introductions/1
  # DELETE /introductions/1.json
  def destroy
    @introduction.destroy
    respond_to do |format|
      format.html { redirect_to introductions_url, notice: 'Introduction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_introduction
      @introduction = Introduction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def introduction_params
      params.require(:introduction).permit(:scheduled_intro_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/introductions_helper.rb
module IntroductionsHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :is_being_onboarded %>
    <%= form.check_box :is_being_onboarded, id: :employee_is_being_onboarded %>
  </div>

  <div class="field">
    <%= form.label :what_i_do %>
    <%= form.text_area :what_i_do, id: :employee_what_i_do %>
  </div>

  <div class="field">
    <%= form.label :fun_fact %>
    <%= form.text_area :fun_fact, id: :employee_fun_fact %>
  </div>

  <div class="field">
    <%= form.label :slack_username %>
    <%= form.text_field :slack_username, id: :employee_slack_username %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>

<table>
  <thead>
    <tr>
      <th>Is being onboarded</th>
      <th>What i do</th>
      <th>Fun fact</th>
      <th>Slack username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.is_being_onboarded %></td>
        <td><%= employee.what_i_do %></td>
        <td><%= employee.fun_fact %></td>
        <td><%= employee.slack_username %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Is being onboarded:</strong>
  <%= @employee.is_being_onboarded %>
</p>

<p>
  <strong>What i do:</strong>
  <%= @employee.what_i_do %>
</p>

<p>
  <strong>Fun fact:</strong>
  <%= @employee.fun_fact %>
</p>

<p>
  <strong>Slack username:</strong>
  <%= @employee.slack_username %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/introductions/_form.html.erb
<%= form_with(model: introduction, local: true) do |form| %>
  <% if introduction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(introduction.errors.count, "error") %> prohibited this introduction from being saved:</h2>

      <ul>
      <% introduction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :scheduled_intro_date %>
    <%= form.datetime_select :scheduled_intro_date, id: :introduction_scheduled_intro_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/introductions/edit.html.erb
<h1>Editing Introduction</h1>

<%= render 'form', introduction: @introduction %>

<%= link_to 'Show', @introduction %> |
<%= link_to 'Back', introductions_path %>

app/views/introductions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Introductions</h1>

<table>
  <thead>
    <tr>
      <th>Scheduled intro date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @introductions.each do |introduction| %>
      <tr>
        <td><%= introduction.scheduled_intro_date %></td>
        <td><%= link_to 'Show', introduction %></td>
        <td><%= link_to 'Edit', edit_introduction_path(introduction) %></td>
        <td><%= link_to 'Destroy', introduction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Introduction', new_introduction_path %>

app/views/introductions/new.html.erb
<h1>New Introduction</h1>

<%= render 'form', introduction: @introduction %>

<%= link_to 'Back', introductions_path %>

app/views/introductions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Scheduled intro date:</strong>
  <%= @introduction.scheduled_intro_date %>
</p>

<%= link_to 'Edit', edit_introduction_path(@introduction) %> |
<%= link_to 'Back', introductions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Introbot</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>